echo "Cloning into UltronMusic ...."
echo "+-+ +-+ +-+ +-+ +-+ +-+  +-+ +-+ +-+ +-+ +-+"
echo "|U| |L| |T| |R| |O| |N|  |M| |U| |S| |I| |C|"
echo "+-+ +-+ +-+ +-+ +-+ +-+  +-+ +-+ +-+ +-+ +-+"
echo "Starting Ultron VC Player for Telegram ...."
echo "╔╦╗─╔╗─────────╔═╦═╗─╔═╦╗"
echo "║║╠╗║╚╦╦╦═╦═╦╗ ║║║║╠╦╣═╬╬═╗"
echo "║║║╚╣╔╣╔╣╬║║║║ ║║║║║║╠═║║═╣"
echo "╚═╩═╩═╩╝╚═╩╩═╝ ╚╩═╩╩═╩═╩╩═╝"
python3 music.py
